---
- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_info:
     cloud: ospcloud
     server: 'frontendi
    register: result
    tags:
      - osp.smoke

  - name: Curl website
    uri:
      url: "http://{{ result.openstack_servers[0].accessIPv4 }}"
      return_content: yes
      status_code: 200
    register: webpage
    failed_when: "'Ansible has done its job' not in webpage.results[0].content"
