ks file for osp-facts
   - name: Fetch Instance Info
     os_server_info:
      cloud: ospcloud
      region_name: RegionOne
     register: openstack_info

# Add hosts to server group
   - name: Add host to group
     add_host:
      name: "{{ server.public_v4 }}"
      groups:
	- "{{ server.metadata.group }}"
	- "{{ server.metadata.deployment_name }}"
      # ansible_ssh_private_key_file: ~/.ssh/openstack.pem
      # ansible_ssh_user: cloud-user
     loop:
       "{{ openstack_info.openstack_servers }}"
     loop_control:
       loop_var: server
       label: "{{ server.hostname }}"
