- name: Create Homework Assignment project 
# Use tower module or tower-cli to create Ansible Tower project. Name of the project is specifed in ./vars/main.yml
  tower_project:
    name: "{{ proj_name }}"
    description: "Homework Assignment project"
    organization: "{{ org_name }}"
    state: present
#    local_path: "/root/ansible_advance_homework"
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    validate_certs: "no"

- name: Machine Credential to connect to workstation using openstack.pub
  tower_credential:
    name: Connect_to_workstation
    state: present
    kind: ssh
    organization: "{{ org_name }}"    
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    ssh_key_data: "{{ lookup('file','{{ user_cred_path }}') }}"
    username: "{{ user_cred_name }}"
    validate_certs: "no"

- name: Create Inventory
  command: |
    tower-cli inventory create -n "{{static_inventory_name}}" --organization "{{org_name}}"

- name: Create Group in static inventory 
  command: |
    tower-cli group create --inventory "{{static_inventory_name}}"  --name {{group_name}}

- name: Add workstation host in tower_inventory 
  command: |
    tower-cli host create --inventory "{{static_inventory_name}}" --name "{{host_name}}"

- name: Associate workstation host to group 
  command: | 
    tower-cli host associate --host "{{host_name}}" --group "{{group_name}}"


- name: Tower Creds key file
  tower_credential:
    name: "{{ opentlc_cred_name }}"
    organization: Default
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    validate_certs: "no"
    ssh_key_data: "{{ lookup('file','/root/.ssh/opentlc_rsa') }}"
    username: "{{ opentlc_login }}"

- name: Remove secret
  file:
    name: /root/secret.pem
    state: absent

